### ISSUE TITLE
Comaintainership of `flac` library

### ISSUE THREAD

**Issue by rockbmb** [mrkkrp/flac#16]
Hello,

I saw your post on [Reddit](https://www.reddit.com/r/haskell/comments/9g00oj/looking_for_comaintainers_for_my_opensource/) asking for comaintaners for your open-source projects, and I'd like to volunteer to do so for this library.

**Comment by mrkkrp** [comment]
Thanks! I added you as a collaborator on GitHub, you should have received an invitation. I'm going to add you on Hackage so you can do revisions and new releases if necessary. What is your Hackage user name?

**Comment by rockbmb** [comment]
@mrkkrp I'm trying to create one right now, but I can't receive any confirmation emails to activate it. I'll keep trying to fix this.

**Comment by mrkkrp** [comment]
Any luck with it?

**Comment by mrkkrp** [comment]
Any progress with Hackage registration?

**Comment by rockbmb** [comment]
@mrkkrp I just fixed it (with the help of u/gbaz1 on Reddit) - you can add me as rockbmb.

**Comment by mrkkrp** [comment]
Done!
